version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: io.grpc:grpc-all
    versions:
    - 1.36.0
    - 1.36.1
